name: "Build Windows/ Linux / ARM macOS"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Build binaries
        run: yarn run build-ci

      - name: Compress x86 build
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./          
          files: |
            ./prebuilds/linux/index.node
          outPath: cider_utils-v0.1.1-napi-v6-linux-x64.tar.gz    

       # Runs a set of commands using the runners shell
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: linux
          # A file, directory or wildcard pattern that describes what to upload
          path: prebuilds/

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Build binaries
        run: yarn run build-ci
      - name: Compress x86 build
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./prebuilds/win32/index.node
          outPath: cider_utils-v0.1.1-napi-v6-win32-x64.tar.gz   
       # Runs a set of commands using the runners shell
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: windows
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.tar.gz

  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Build binaries
        run: yarn run build-ci

      - name: Move to arm
        run: rustup target add aarch64-apple-darwin  

      - name: Build binaries
        run: yarn run build-ci-m1
      - name: Compress x86 build
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./prebuilds/mac-x86/index.node
          outPath: cider_utils-v0.1.1-napi-v6-darwin-x64.tar.gz 
      - name: Compress arm build
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./prebuilds/mac-arm/index.node
          outPath: cider_utils-v0.1.1-napi-v6-darwin-arm64.tar.gz           
       # Runs a set of commands using the runners shell
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: macos
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.tar.gz       
                
  final:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    steps:
      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R